# Generated by Django 3.0.5 on 2020-06-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
    ]
