# Generated by Django 3.0.5 on 2020-06-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0002_auto_20200602_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
