# Generated by Django 3.0.5 on 2020-06-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0004_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='showInfo.UserGroup'),
        ),
    ]
