# Generated by Django 3.0.5 on 2020-06-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0005_userinfo_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='showInfo.Boy')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='showInfo.Girl')),
            ],
        ),
    ]
