# Generated by Django 3.0.5 on 2020-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0006_boy_girl_love'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(to='showInfo.Girl'),
        ),
        migrations.DeleteModel(
            name='Love',
        ),
    ]
