# Generated by Django 3.0.5 on 2020-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showInfo', '0007_auto_20200608_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('nid', models.IntegerField(blank=True, error_messages={'null': '编号为空'}, help_text='用户编号', primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(default='zhangsan', max_length=32, null=True)),
            ],
        ),
    ]
