# Generated by Django 2.2 on 2020-06-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='boy_id',
            new_name='boy',
        ),
        migrations.RenameField(
            model_name='love',
            old_name='girl_id',
            new_name='girl',
        ),
    ]
