# Generated by Django 2.2 on 2020-07-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200628_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='boy',
            name='girl',
            field=models.ManyToManyField(to='app01.Girl'),
        ),
        migrations.DeleteModel(
            name='Love',
        ),
    ]
