# Generated by Django 2.2 on 2020-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_u2u_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='m',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
